// Code generated by github.com/efritz/go-mockgen 0.1.0; DO NOT EDIT.

package mocks

import (
	"context"
	indexmanager "github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-indexer/internal/index_manager"
	types "github.com/sourcegraph/sourcegraph/enterprise/internal/codeintel/queue/types"
	store "github.com/sourcegraph/sourcegraph/enterprise/internal/codeintel/store"
	"sync"
)

// MockManager is a mock implementation of the Manager interface (from the
// package
// github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-indexer/internal/index_manager)
// used for unit testing.
type MockManager struct {
	// CompleteFunc is an instance of a mock function object controlling the
	// behavior of the method Complete.
	CompleteFunc *ManagerCompleteFunc
	// DequeueFunc is an instance of a mock function object controlling the
	// behavior of the method Dequeue.
	DequeueFunc *ManagerDequeueFunc
	// HeartbeatFunc is an instance of a mock function object controlling
	// the behavior of the method Heartbeat.
	HeartbeatFunc *ManagerHeartbeatFunc
}

// NewMockManager creates a new mock of the Manager interface. All methods
// return zero values for all results, unless overwritten.
func NewMockManager() *MockManager {
	return &MockManager{
		CompleteFunc: &ManagerCompleteFunc{
			defaultHook: func(context.Context, types.CompleteRequest) (bool, error) {
				return false, nil
			},
		},
		DequeueFunc: &ManagerDequeueFunc{
			defaultHook: func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
				return store.Index{}, false, nil
			},
		},
		HeartbeatFunc: &ManagerHeartbeatFunc{
			defaultHook: func(context.Context, types.HeartbeatRequest) error {
				return nil
			},
		},
	}
}

// NewMockManagerFrom creates a new mock of the MockManager interface. All
// methods delegate to the given implementation, unless overwritten.
func NewMockManagerFrom(i indexmanager.Manager) *MockManager {
	return &MockManager{
		CompleteFunc: &ManagerCompleteFunc{
			defaultHook: i.Complete,
		},
		DequeueFunc: &ManagerDequeueFunc{
			defaultHook: i.Dequeue,
		},
		HeartbeatFunc: &ManagerHeartbeatFunc{
			defaultHook: i.Heartbeat,
		},
	}
}

// ManagerCompleteFunc describes the behavior when the Complete method of
// the parent MockManager instance is invoked.
type ManagerCompleteFunc struct {
	defaultHook func(context.Context, types.CompleteRequest) (bool, error)
	hooks       []func(context.Context, types.CompleteRequest) (bool, error)
	history     []ManagerCompleteFuncCall
	mutex       sync.Mutex
}

// Complete delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockManager) Complete(v0 context.Context, v1 types.CompleteRequest) (bool, error) {
	r0, r1 := m.CompleteFunc.nextHook()(v0, v1)
	m.CompleteFunc.appendCall(ManagerCompleteFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Complete method of
// the parent MockManager instance is invoked and the hook queue is empty.
func (f *ManagerCompleteFunc) SetDefaultHook(hook func(context.Context, types.CompleteRequest) (bool, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Complete method of the parent MockManager instance inovkes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *ManagerCompleteFunc) PushHook(hook func(context.Context, types.CompleteRequest) (bool, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ManagerCompleteFunc) SetDefaultReturn(r0 bool, r1 error) {
	f.SetDefaultHook(func(context.Context, types.CompleteRequest) (bool, error) {
		return r0, r1
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ManagerCompleteFunc) PushReturn(r0 bool, r1 error) {
	f.PushHook(func(context.Context, types.CompleteRequest) (bool, error) {
		return r0, r1
	})
}

func (f *ManagerCompleteFunc) nextHook() func(context.Context, types.CompleteRequest) (bool, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ManagerCompleteFunc) appendCall(r0 ManagerCompleteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ManagerCompleteFuncCall objects describing
// the invocations of this function.
func (f *ManagerCompleteFunc) History() []ManagerCompleteFuncCall {
	f.mutex.Lock()
	history := make([]ManagerCompleteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ManagerCompleteFuncCall is an object that describes an invocation of
// method Complete on an instance of MockManager.
type ManagerCompleteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.CompleteRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 bool
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ManagerCompleteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ManagerCompleteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// ManagerDequeueFunc describes the behavior when the Dequeue method of the
// parent MockManager instance is invoked.
type ManagerDequeueFunc struct {
	defaultHook func(context.Context, types.DequeueRequest) (store.Index, bool, error)
	hooks       []func(context.Context, types.DequeueRequest) (store.Index, bool, error)
	history     []ManagerDequeueFuncCall
	mutex       sync.Mutex
}

// Dequeue delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockManager) Dequeue(v0 context.Context, v1 types.DequeueRequest) (store.Index, bool, error) {
	r0, r1, r2 := m.DequeueFunc.nextHook()(v0, v1)
	m.DequeueFunc.appendCall(ManagerDequeueFuncCall{v0, v1, r0, r1, r2})
	return r0, r1, r2
}

// SetDefaultHook sets function that is called when the Dequeue method of
// the parent MockManager instance is invoked and the hook queue is empty.
func (f *ManagerDequeueFunc) SetDefaultHook(hook func(context.Context, types.DequeueRequest) (store.Index, bool, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Dequeue method of the parent MockManager instance inovkes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *ManagerDequeueFunc) PushHook(hook func(context.Context, types.DequeueRequest) (store.Index, bool, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ManagerDequeueFunc) SetDefaultReturn(r0 store.Index, r1 bool, r2 error) {
	f.SetDefaultHook(func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
		return r0, r1, r2
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ManagerDequeueFunc) PushReturn(r0 store.Index, r1 bool, r2 error) {
	f.PushHook(func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
		return r0, r1, r2
	})
}

func (f *ManagerDequeueFunc) nextHook() func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ManagerDequeueFunc) appendCall(r0 ManagerDequeueFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ManagerDequeueFuncCall objects describing
// the invocations of this function.
func (f *ManagerDequeueFunc) History() []ManagerDequeueFuncCall {
	f.mutex.Lock()
	history := make([]ManagerDequeueFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ManagerDequeueFuncCall is an object that describes an invocation of
// method Dequeue on an instance of MockManager.
type ManagerDequeueFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.DequeueRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 store.Index
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 bool
	// Result2 is the value of the 3rd result returned from this method
	// invocation.
	Result2 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ManagerDequeueFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ManagerDequeueFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1, c.Result2}
}

// ManagerHeartbeatFunc describes the behavior when the Heartbeat method of
// the parent MockManager instance is invoked.
type ManagerHeartbeatFunc struct {
	defaultHook func(context.Context, types.HeartbeatRequest) error
	hooks       []func(context.Context, types.HeartbeatRequest) error
	history     []ManagerHeartbeatFuncCall
	mutex       sync.Mutex
}

// Heartbeat delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockManager) Heartbeat(v0 context.Context, v1 types.HeartbeatRequest) error {
	r0 := m.HeartbeatFunc.nextHook()(v0, v1)
	m.HeartbeatFunc.appendCall(ManagerHeartbeatFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Heartbeat method of
// the parent MockManager instance is invoked and the hook queue is empty.
func (f *ManagerHeartbeatFunc) SetDefaultHook(hook func(context.Context, types.HeartbeatRequest) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Heartbeat method of the parent MockManager instance inovkes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *ManagerHeartbeatFunc) PushHook(hook func(context.Context, types.HeartbeatRequest) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ManagerHeartbeatFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(context.Context, types.HeartbeatRequest) error {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ManagerHeartbeatFunc) PushReturn(r0 error) {
	f.PushHook(func(context.Context, types.HeartbeatRequest) error {
		return r0
	})
}

func (f *ManagerHeartbeatFunc) nextHook() func(context.Context, types.HeartbeatRequest) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ManagerHeartbeatFunc) appendCall(r0 ManagerHeartbeatFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ManagerHeartbeatFuncCall objects describing
// the invocations of this function.
func (f *ManagerHeartbeatFunc) History() []ManagerHeartbeatFuncCall {
	f.mutex.Lock()
	history := make([]ManagerHeartbeatFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ManagerHeartbeatFuncCall is an object that describes an invocation of
// method Heartbeat on an instance of MockManager.
type ManagerHeartbeatFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.HeartbeatRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ManagerHeartbeatFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ManagerHeartbeatFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// MockThreadedManager is a mock implementation of the ThreadedManager
// interface (from the package
// github.com/sourcegraph/sourcegraph/enterprise/cmd/precise-code-intel-indexer/internal/index_manager)
// used for unit testing.
type MockThreadedManager struct {
	// CompleteFunc is an instance of a mock function object controlling the
	// behavior of the method Complete.
	CompleteFunc *ThreadedManagerCompleteFunc
	// DequeueFunc is an instance of a mock function object controlling the
	// behavior of the method Dequeue.
	DequeueFunc *ThreadedManagerDequeueFunc
	// HeartbeatFunc is an instance of a mock function object controlling
	// the behavior of the method Heartbeat.
	HeartbeatFunc *ThreadedManagerHeartbeatFunc
	// StartFunc is an instance of a mock function object controlling the
	// behavior of the method Start.
	StartFunc *ThreadedManagerStartFunc
	// StopFunc is an instance of a mock function object controlling the
	// behavior of the method Stop.
	StopFunc *ThreadedManagerStopFunc
}

// NewMockThreadedManager creates a new mock of the ThreadedManager
// interface. All methods return zero values for all results, unless
// overwritten.
func NewMockThreadedManager() *MockThreadedManager {
	return &MockThreadedManager{
		CompleteFunc: &ThreadedManagerCompleteFunc{
			defaultHook: func(context.Context, types.CompleteRequest) (bool, error) {
				return false, nil
			},
		},
		DequeueFunc: &ThreadedManagerDequeueFunc{
			defaultHook: func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
				return store.Index{}, false, nil
			},
		},
		HeartbeatFunc: &ThreadedManagerHeartbeatFunc{
			defaultHook: func(context.Context, types.HeartbeatRequest) error {
				return nil
			},
		},
		StartFunc: &ThreadedManagerStartFunc{
			defaultHook: func() {
				return
			},
		},
		StopFunc: &ThreadedManagerStopFunc{
			defaultHook: func() {
				return
			},
		},
	}
}

// NewMockThreadedManagerFrom creates a new mock of the MockThreadedManager
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockThreadedManagerFrom(i indexmanager.ThreadedManager) *MockThreadedManager {
	return &MockThreadedManager{
		CompleteFunc: &ThreadedManagerCompleteFunc{
			defaultHook: i.Complete,
		},
		DequeueFunc: &ThreadedManagerDequeueFunc{
			defaultHook: i.Dequeue,
		},
		HeartbeatFunc: &ThreadedManagerHeartbeatFunc{
			defaultHook: i.Heartbeat,
		},
		StartFunc: &ThreadedManagerStartFunc{
			defaultHook: i.Start,
		},
		StopFunc: &ThreadedManagerStopFunc{
			defaultHook: i.Stop,
		},
	}
}

// ThreadedManagerCompleteFunc describes the behavior when the Complete
// method of the parent MockThreadedManager instance is invoked.
type ThreadedManagerCompleteFunc struct {
	defaultHook func(context.Context, types.CompleteRequest) (bool, error)
	hooks       []func(context.Context, types.CompleteRequest) (bool, error)
	history     []ThreadedManagerCompleteFuncCall
	mutex       sync.Mutex
}

// Complete delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockThreadedManager) Complete(v0 context.Context, v1 types.CompleteRequest) (bool, error) {
	r0, r1 := m.CompleteFunc.nextHook()(v0, v1)
	m.CompleteFunc.appendCall(ThreadedManagerCompleteFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Complete method of
// the parent MockThreadedManager instance is invoked and the hook queue is
// empty.
func (f *ThreadedManagerCompleteFunc) SetDefaultHook(hook func(context.Context, types.CompleteRequest) (bool, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Complete method of the parent MockThreadedManager instance inovkes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *ThreadedManagerCompleteFunc) PushHook(hook func(context.Context, types.CompleteRequest) (bool, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ThreadedManagerCompleteFunc) SetDefaultReturn(r0 bool, r1 error) {
	f.SetDefaultHook(func(context.Context, types.CompleteRequest) (bool, error) {
		return r0, r1
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ThreadedManagerCompleteFunc) PushReturn(r0 bool, r1 error) {
	f.PushHook(func(context.Context, types.CompleteRequest) (bool, error) {
		return r0, r1
	})
}

func (f *ThreadedManagerCompleteFunc) nextHook() func(context.Context, types.CompleteRequest) (bool, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ThreadedManagerCompleteFunc) appendCall(r0 ThreadedManagerCompleteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ThreadedManagerCompleteFuncCall objects
// describing the invocations of this function.
func (f *ThreadedManagerCompleteFunc) History() []ThreadedManagerCompleteFuncCall {
	f.mutex.Lock()
	history := make([]ThreadedManagerCompleteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ThreadedManagerCompleteFuncCall is an object that describes an invocation
// of method Complete on an instance of MockThreadedManager.
type ThreadedManagerCompleteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.CompleteRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 bool
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ThreadedManagerCompleteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ThreadedManagerCompleteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// ThreadedManagerDequeueFunc describes the behavior when the Dequeue method
// of the parent MockThreadedManager instance is invoked.
type ThreadedManagerDequeueFunc struct {
	defaultHook func(context.Context, types.DequeueRequest) (store.Index, bool, error)
	hooks       []func(context.Context, types.DequeueRequest) (store.Index, bool, error)
	history     []ThreadedManagerDequeueFuncCall
	mutex       sync.Mutex
}

// Dequeue delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockThreadedManager) Dequeue(v0 context.Context, v1 types.DequeueRequest) (store.Index, bool, error) {
	r0, r1, r2 := m.DequeueFunc.nextHook()(v0, v1)
	m.DequeueFunc.appendCall(ThreadedManagerDequeueFuncCall{v0, v1, r0, r1, r2})
	return r0, r1, r2
}

// SetDefaultHook sets function that is called when the Dequeue method of
// the parent MockThreadedManager instance is invoked and the hook queue is
// empty.
func (f *ThreadedManagerDequeueFunc) SetDefaultHook(hook func(context.Context, types.DequeueRequest) (store.Index, bool, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Dequeue method of the parent MockThreadedManager instance inovkes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *ThreadedManagerDequeueFunc) PushHook(hook func(context.Context, types.DequeueRequest) (store.Index, bool, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ThreadedManagerDequeueFunc) SetDefaultReturn(r0 store.Index, r1 bool, r2 error) {
	f.SetDefaultHook(func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
		return r0, r1, r2
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ThreadedManagerDequeueFunc) PushReturn(r0 store.Index, r1 bool, r2 error) {
	f.PushHook(func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
		return r0, r1, r2
	})
}

func (f *ThreadedManagerDequeueFunc) nextHook() func(context.Context, types.DequeueRequest) (store.Index, bool, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ThreadedManagerDequeueFunc) appendCall(r0 ThreadedManagerDequeueFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ThreadedManagerDequeueFuncCall objects
// describing the invocations of this function.
func (f *ThreadedManagerDequeueFunc) History() []ThreadedManagerDequeueFuncCall {
	f.mutex.Lock()
	history := make([]ThreadedManagerDequeueFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ThreadedManagerDequeueFuncCall is an object that describes an invocation
// of method Dequeue on an instance of MockThreadedManager.
type ThreadedManagerDequeueFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.DequeueRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 store.Index
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 bool
	// Result2 is the value of the 3rd result returned from this method
	// invocation.
	Result2 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ThreadedManagerDequeueFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ThreadedManagerDequeueFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1, c.Result2}
}

// ThreadedManagerHeartbeatFunc describes the behavior when the Heartbeat
// method of the parent MockThreadedManager instance is invoked.
type ThreadedManagerHeartbeatFunc struct {
	defaultHook func(context.Context, types.HeartbeatRequest) error
	hooks       []func(context.Context, types.HeartbeatRequest) error
	history     []ThreadedManagerHeartbeatFuncCall
	mutex       sync.Mutex
}

// Heartbeat delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockThreadedManager) Heartbeat(v0 context.Context, v1 types.HeartbeatRequest) error {
	r0 := m.HeartbeatFunc.nextHook()(v0, v1)
	m.HeartbeatFunc.appendCall(ThreadedManagerHeartbeatFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Heartbeat method of
// the parent MockThreadedManager instance is invoked and the hook queue is
// empty.
func (f *ThreadedManagerHeartbeatFunc) SetDefaultHook(hook func(context.Context, types.HeartbeatRequest) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Heartbeat method of the parent MockThreadedManager instance inovkes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *ThreadedManagerHeartbeatFunc) PushHook(hook func(context.Context, types.HeartbeatRequest) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ThreadedManagerHeartbeatFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(context.Context, types.HeartbeatRequest) error {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ThreadedManagerHeartbeatFunc) PushReturn(r0 error) {
	f.PushHook(func(context.Context, types.HeartbeatRequest) error {
		return r0
	})
}

func (f *ThreadedManagerHeartbeatFunc) nextHook() func(context.Context, types.HeartbeatRequest) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ThreadedManagerHeartbeatFunc) appendCall(r0 ThreadedManagerHeartbeatFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ThreadedManagerHeartbeatFuncCall objects
// describing the invocations of this function.
func (f *ThreadedManagerHeartbeatFunc) History() []ThreadedManagerHeartbeatFuncCall {
	f.mutex.Lock()
	history := make([]ThreadedManagerHeartbeatFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ThreadedManagerHeartbeatFuncCall is an object that describes an
// invocation of method Heartbeat on an instance of MockThreadedManager.
type ThreadedManagerHeartbeatFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 types.HeartbeatRequest
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ThreadedManagerHeartbeatFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ThreadedManagerHeartbeatFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// ThreadedManagerStartFunc describes the behavior when the Start method of
// the parent MockThreadedManager instance is invoked.
type ThreadedManagerStartFunc struct {
	defaultHook func()
	hooks       []func()
	history     []ThreadedManagerStartFuncCall
	mutex       sync.Mutex
}

// Start delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockThreadedManager) Start() {
	m.StartFunc.nextHook()()
	m.StartFunc.appendCall(ThreadedManagerStartFuncCall{})
	return
}

// SetDefaultHook sets function that is called when the Start method of the
// parent MockThreadedManager instance is invoked and the hook queue is
// empty.
func (f *ThreadedManagerStartFunc) SetDefaultHook(hook func()) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Start method of the parent MockThreadedManager instance inovkes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *ThreadedManagerStartFunc) PushHook(hook func()) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ThreadedManagerStartFunc) SetDefaultReturn() {
	f.SetDefaultHook(func() {
		return
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ThreadedManagerStartFunc) PushReturn() {
	f.PushHook(func() {
		return
	})
}

func (f *ThreadedManagerStartFunc) nextHook() func() {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ThreadedManagerStartFunc) appendCall(r0 ThreadedManagerStartFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ThreadedManagerStartFuncCall objects
// describing the invocations of this function.
func (f *ThreadedManagerStartFunc) History() []ThreadedManagerStartFuncCall {
	f.mutex.Lock()
	history := make([]ThreadedManagerStartFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ThreadedManagerStartFuncCall is an object that describes an invocation of
// method Start on an instance of MockThreadedManager.
type ThreadedManagerStartFuncCall struct{}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ThreadedManagerStartFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ThreadedManagerStartFuncCall) Results() []interface{} {
	return []interface{}{}
}

// ThreadedManagerStopFunc describes the behavior when the Stop method of
// the parent MockThreadedManager instance is invoked.
type ThreadedManagerStopFunc struct {
	defaultHook func()
	hooks       []func()
	history     []ThreadedManagerStopFuncCall
	mutex       sync.Mutex
}

// Stop delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockThreadedManager) Stop() {
	m.StopFunc.nextHook()()
	m.StopFunc.appendCall(ThreadedManagerStopFuncCall{})
	return
}

// SetDefaultHook sets function that is called when the Stop method of the
// parent MockThreadedManager instance is invoked and the hook queue is
// empty.
func (f *ThreadedManagerStopFunc) SetDefaultHook(hook func()) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Stop method of the parent MockThreadedManager instance inovkes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *ThreadedManagerStopFunc) PushHook(hook func()) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *ThreadedManagerStopFunc) SetDefaultReturn() {
	f.SetDefaultHook(func() {
		return
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *ThreadedManagerStopFunc) PushReturn() {
	f.PushHook(func() {
		return
	})
}

func (f *ThreadedManagerStopFunc) nextHook() func() {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ThreadedManagerStopFunc) appendCall(r0 ThreadedManagerStopFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ThreadedManagerStopFuncCall objects
// describing the invocations of this function.
func (f *ThreadedManagerStopFunc) History() []ThreadedManagerStopFuncCall {
	f.mutex.Lock()
	history := make([]ThreadedManagerStopFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ThreadedManagerStopFuncCall is an object that describes an invocation of
// method Stop on an instance of MockThreadedManager.
type ThreadedManagerStopFuncCall struct{}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ThreadedManagerStopFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ThreadedManagerStopFuncCall) Results() []interface{} {
	return []interface{}{}
}
